version: "3"

services:
  gemini-api:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./main.py:/app/main.py
      - ./admin.py:/app/admin.py
      - ./templates:/app/templates
      - ./pyproject.toml:/app/pyproject.toml
      - ./secrets:/app/secrets
    env_file:
      - .env
    restart: unless-stopped
